#base on NVIDIA DL for Pytorch
FROM nvcr.io/nvidia/pytorch:21.03-py3

WORKDIR /
RUN git clone https://github.com/klecki/DeepLearningExamples.git joc
WORKDIR /joc
RUN git checkout dali-aa

RUN pip list | grep dali
# The container always lacks this
RUN pip install nvidia-pyindex
RUN pip install nvidia-dllogger

COPY wheelhouse/nvidia_dali_cuda110* /whl/

# currently container has cuda 11
RUN pip uninstall -y nvidia-dali-cuda110
RUN pip install /whl/nvidia_dali_cuda110*

WORKDIR /joc/PyTorch/Classification/ConvNets/