#base on NVIDIA DL for Pytorch
FROM nvcr.io/nvidia/pytorch:23.01-py3

WORKDIR /
RUN git clone https://github.com/stiepan/DeepLearningExamples joc
WORKDIR /joc
RUN git checkout aa_no_arithm

RUN pip list | grep dali
# The container always lacks this
RUN pip install nvidia-dllogger

COPY wheelhouse/nvidia_dali_cuda120* /whl/

# currently container has cuda 11
RUN pip uninstall -y nvidia-dali-cuda110
RUN pip install /whl/nvidia_dali_cuda120*

WORKDIR /joc/PyTorch/Classification/ConvNets/